### ISSUE TITLE
Better test pod, and some minor things

### ISSUE THREAD

**Issue by uablrek** [LionelJouin/network-dra#1]
The test pod should use a commonly available image, e.g. "alpine". This works:
```yaml
---
apiVersion: resource.k8s.io/v1alpha2
kind: ResourceClaim
metadata:
  name: my-net
spec:
  resourceClassName: dra.networking
---
apiVersion: v1
kind: Pod
metadata:
  name: my-net-pod
spec:
  containers:
    - name: alpine
      image: alpine:latest
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: false
      command:
        - sleep
        - infinity
      resources:
        claims:
        - name: my-net
  resourceClaims:
  - name: my-net
    source:
      resourceClaimName: my-net
```

Kind config has a "runtimeConfig" section that should be used rather than passing "extraArgs" to the api-server:
```yaml
runtimeConfig:
  "networking.k8s.io/v1alpha1": true
  "resource.k8s.io/v1alpha2": true
```

And (nit):
```
kind create cluster --config examples/kind.yaml
```
in the readme (the "s" is missing).
